---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, Trident, trident for docker, docker, logs, binary, managed plugin 
summary: トラブルシューティングに役立つログを収集できます。ログを収集するために使用する方法は、Docker プラグインの実行方法によって異なります。 
---
= ログを収集する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
トラブルシューティングに役立つログを収集できます。ログを収集するために使用する方法は、Docker プラグインの実行方法によって異なります。



[[collect-logs-for-troubleshooting]]
== トラブルシューティングのためにログを収集する

.手順
. 推奨Tridentれる管理プラグイン方式（つまり、 `docker plugin`コマンド) については、次のように表示します。
+
[source, console]
----
docker plugin ls
----
+
[listing]
----
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
標準のログ レベルでは、ほとんどの問題を診断できます。それだけでは不十分な場合は、デバッグ ログを有効にすることができます。

. デバッグ ログを有効にするには、デバッグ ログを有効にしたプラグインをインストールします。
+
[source, console]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
または、プラグインがすでにインストールされている場合は、デバッグ ログを有効にします。

+
[source, console]
----
docker plugin disable <plugin>
----
+
[source, console]
----
docker plugin set <plugin> debug=true
----
+
[source, console]
----
docker plugin enable <plugin>
----
. バイナリ自体をホスト上で実行している場合、ログはホストの `/var/log/netappdvp`ディレクトリ。デバッグログを有効にするには、以下を指定します。 `-debug`プラグインを実行するとき。




[[general-troubleshooting-tips]]
== 一般的なトラブルシューティングのヒント

* 新しいユーザーが遭遇する最も一般的な問題は、プラグインの初期化を妨げる誤った構成です。このような場合、プラグインをインストールまたは有効化しようとすると、次のようなメッセージが表示される可能性があります。
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
これは、プラグインの起動に失敗したことを意味します。幸いなことに、このプラグインは包括的なログ機能が組み込まれているため、発生する可能性のあるほとんどの問題の診断に役立ちます。

* PVをコンテナにマウントする際に問題がある場合は、 `rpcbind`インストールされ実行されています。ホストOSに必要なパッケージマネージャーを使用して、 `rpcbind`実行中です。  rpcbindサービスの状態を確認するには、 `systemctl status rpcbind`またはそれと同等のもの。

