---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, Trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config, nvme/tcp, nvme 
summary: Trident を展開する前に、ホストに必要なプロトコルの前提条件をインストールして構成する必要があります。 
---
= 展開の前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident を展開する前に、ホストに必要なプロトコルの前提条件をインストールして構成する必要があります。



[[verify-the-requirements]]
== 要件を確認する

* 導入がすべての要件を満たしていることを確認するlink:../trident-get-started/requirements.html["要件"]。
* サポートされているバージョンの Docker がインストールされていることを確認します。  Dockerのバージョンが古い場合は、 https://docs.docker.com/engine/install/["インストールまたはアップデートする"^] 。
+
[source, console]
----
docker --version
----
* プロトコルの前提条件がホストにインストールされ、構成されていることを確認します。




[[nfs-tools]]
=== NFSツール

オペレーティング システムのコマンドを使用して NFS ツールをインストールします。

[role="tabbed-block"]
====
.RHEL 8以降
--
[source, console]
----
sudo yum install -y nfs-utils
----
--
.Ubuntu
--
[source, console]
----
sudo apt-get install -y nfs-common
----
--
====

WARNING: ボリュームをコンテナに接続するときに障害が発生しないように、NFS ツールをインストールした後、ワーカー ノードを再起動します。



[[iscsi-tools]]
=== iSCSIツール

オペレーティング システムのコマンドを使用して iSCSI ツールをインストールします。

[role="tabbed-block"]
====
.RHEL 8以降
--
. 次のシステム パッケージをインストールします。
+
[source, console]
----
sudo yum install -y lsscsi iscsi-initiator-utils sg3_utils device-mapper-multipath
----
. iscsi-initiator-utils のバージョンが 6.2.0.874-2.el7 以降であることを確認します。
+
[source, console]
----
rpm -q iscsi-initiator-utils
----
. スキャンを手動に設定します:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. マルチパスを有効にする:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 確保する `etc/multipath.conf`含む `find_multipaths no`下 `defaults`。

. 確実に `iscsid`そして `multipathd`実行中:
+
[source, console]
----
sudo systemctl enable --now iscsid multipathd
----
. 有効化して起動 `iscsi`:
+
[source, console]
----
sudo systemctl enable --now iscsi
----


--
.Ubuntu
--
. 次のシステム パッケージをインストールします。
+
[source, console]
----
sudo apt-get install -y open-iscsi lsscsi sg3-utils multipath-tools scsitools
----
. open-iscsi のバージョンが 2.0.874-5ubuntu2.10 以降 (bionic の場合) または 2.0.874-7.1ubuntu6.1 以降 (focal の場合) であることを確認します。
+
[source, console]
----
dpkg -l open-iscsi
----
. スキャンを手動に設定します:
+
[source, console]
----
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf
----
. マルチパスを有効にする:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 確保する `etc/multipath.conf`含む `find_multipaths no`下 `defaults`。

. 確実に `open-iscsi`そして `multipath-tools`有効になっていて実行中である:
+
[source, console]
----
sudo systemctl status multipath-tools
sudo systemctl enable --now open-iscsi.service
sudo systemctl status open-iscsi
----


--
====


[[nvme-tools]]
== NVMeツール

オペレーティング システムのコマンドを使用して NVMe ツールをインストールします。

[NOTE]
====
* NVMe には RHEL 9 以降が必要です。
* Kubernetes ノードのカーネル バージョンが古すぎる場合、またはカーネル バージョンで NVMe パッケージが利用できない場合は、ノードのカーネル バージョンを NVMe パッケージを含むバージョンに更新する必要がある場合があります。


====
[role="tabbed-block"]
====
.RHEL 9
--
[source, console]
----
sudo yum install nvme-cli
sudo yum install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
.Ubuntu
--
[source, console]
----
sudo apt install nvme-cli
sudo apt -y install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
----
--
====


[[fc-tools]]
== FCツール

オペレーティング システムのコマンドを使用して FC ツールをインストールします。

* FC PVでRHEL/Red Hat Enterprise Linux CoreOS (RHCOS)を実行するワーカーノードを使用する場合は、 `discard`インライン スペース再利用を実行するには、StorageClass の mountOption を使用します。参照 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Red Hat ドキュメント"^]。


[role="tabbed-block"]
====
.RHEL 8以降
--
. 次のシステム パッケージをインストールします。
+
[source, console]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. マルチパスを有効にする:
+
[source, console]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: 確保する `etc/multipath.conf`含む `find_multipaths no`下 `defaults`。

. 確実に `multipathd`実行中:
+
[source, console]
----
sudo systemctl enable --now multipathd
----


--
.Ubuntu
--
. 次のシステム パッケージをインストールします。
+
[source, console]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. マルチパスを有効にする:
+
[source, console]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: 確保する `etc/multipath.conf`含む `find_multipaths no`下 `defaults`。

. 確実に `multipath-tools`有効になっていて実行中:
+
[source, console]
----
sudo systemctl status multipath-tools
----


--
====