---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: 各ストレージ ドライバーには異なるオプション セットがあり、ボリュームの作成時に指定して結果をカスタマイズできます。構成されたストレージ システムに適用されるオプションについては、以下を参照してください。 
---
= ドライバー固有のボリュームオプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
各ストレージ ドライバーには異なるオプション セットがあり、ボリュームの作成時に指定して結果をカスタマイズできます。構成されたストレージ システムに適用されるオプションについては、以下を参照してください。

ボリューム作成操作中にこれらのオプションを使用するのは簡単です。オプションと値を指定するには、 `-o` CLI 操作中のオペレータ。これらは、JSON 構成ファイルの同等の値を上書きします。



== ONTAPボリュームオプション

NFS、iSCSI、FC のボリューム作成オプションは次のとおりです。

[cols="2*"]
|===
| オプション | 説明 


| `size`  a| 
ボリュームのサイズ。デフォルトは 1 GiB です。



| `spaceReserve`  a| 
ボリュームをシン プロビジョニングまたはシック プロビジョニングします。デフォルトはシン プロビジョニングです。有効な値は `none`（シンプロビジョニング）および `volume`(シックプロビジョニング)。



| `snapshotPolicy`  a| 
これにより、スナップショット ポリシーが目的の値に設定されます。デフォルトは `none`つまり、ボリュームのスナップショットは自動的に作成されません。ストレージ管理者によって変更されない限り、すべてのONTAPシステムに「default」というポリシーが存在し、6 つの時間別スナップショット、2 つの日次スナップショット、および 2 つの週次スナップショットが作成され、保持されます。スナップショットに保存されたデータは、 `.snapshot`ボリューム内の任意のディレクトリ内のディレクトリ。



| `snapshotReserve`  a| 
これにより、スナップショットの予約が希望のパーセンテージに設定されます。デフォルトでは値がありません。つまり、snapshotPolicy を選択した場合はONTAP はsnapshotReserve (通常 5%) を選択し、snapshotPolicy が none の場合は 0% を選択します。すべてのONTAPバックエンドの構成ファイルでデフォルトの snapshotReserve 値を設定でき、ontap-nas-economy を除くすべてのONTAPバックエンドのボリューム作成オプションとして使用できます。



| `splitOnClone`  a| 
ボリュームのクローンを作成すると、 ONTAP はクローンをその親から直ちに分割します。デフォルトは `false`。ボリュームのクローン作成の一部のユースケースでは、ストレージ効率を高める機会がほとんどないため、作成後すぐにクローンを親から分割するのが最適です。たとえば、空のデータベースのクローンを作成すると、時間は大幅に節約できますが、ストレージの節約はほとんどないため、クローンをすぐに分割するのが最適です。



| `encryption`  a| 
新しいボリュームでNetAppボリューム暗号化（NVE）を有効にします。デフォルトは `false`。このオプションを使用するには、NVE のライセンスを取得し、クラスターで有効にする必要があります。

バックエンドで NAE が有効になっている場合、 Tridentでプロビジョニングされたすべてのボリュームで NAE が有効になります。

詳細については、以下を参照してください。link:../trident-reco/security-reco.html["Trident がNVE および NAE と連携する仕組み"] 。



| `tieringPolicy`  a| 
ボリュームに使用する階層化ポリシーを設定します。これにより、データが非アクティブ (コールド) になったときにクラウド層に移動するか否かが決まります。

|===
次の追加オプションは NFS のみに有効です。

[cols="2*"]
|===
| オプション | 説明 


| `unixPermissions`  a| 
これは、ボリューム自体の権限セットを制御します。デフォルトでは、権限は次のように設定されます。 ``---rwxr-xr-x` 、または数値表記0755、および `root`所有者になります。テキスト形式または数値形式のいずれかが機能します。



| `snapshotDir`  a| 
これを設定 `true`作るだろう `.snapshot`ボリュームにアクセスするクライアントに表示されるディレクトリ。デフォルト値は `false`つまり、 `.snapshot`ディレクトリはデフォルトで無効になっています。一部のイメージ、例えば公式のMySQLイメージは、 `.snapshot`ディレクトリが表示されます。



| `exportPolicy`  a| 
ボリュームに使用するエクスポート ポリシーを設定します。デフォルトは `default`。



| `securityStyle`  a| 
ボリュームへのアクセスに使用するセキュリティ スタイルを設定します。デフォルトは `unix`。有効な値は `unix`そして `mixed`。

|===
次の追加オプションは iSCSI のみに適用されます。

[cols="2*"]
|===
| オプション | 説明 


| `fileSystemType` | iSCSI ボリュームをフォーマットするために使用するファイル システムを設定します。デフォルトは `ext4`。有効な値は `ext3`、 `ext4` 、 そして `xfs`。 


| `spaceAllocation` | これを設定 `false`LUN のスペース割り当て機能をオフにします。デフォルト値は `true`つまり、ボリュームのスペースが不足し、ボリューム内の LUN が書き込みを受け付けることができなくなったときに、 ONTAP はホストに通知します。また、このオプションで、ホストでデータが削除された時点での自動スペース再生も有効になります。 
|===


=== 例

以下の例を参照してください。

* 10 GiB のボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* スナップショット付きの 100 GiB ボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* setUID ビットが有効になっているボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


最小ボリュームサイズは 20 MiB です。

スナップショットリザーブが指定されておらず、スナップショットポリシーが `none`Trident は0% のスナップショット予約を使用します。

* スナップショット ポリシーとスナップショット リザーブのないボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* スナップショット ポリシーがなく、カスタム スナップショット予約が 10% のボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* スナップショット ポリシーと 10% のカスタム スナップショット予約を持つボリュームを作成します。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* スナップショット ポリシーを使用してボリュームを作成し、ONTAP のデフォルトのスナップショット リザーブ (通常は 5%) を受け入れます。
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Elementソフトウェアのボリュームオプション

Element ソフトウェア オプションは、ボリュームに関連付けられたサイズとサービス品質 (QoS) ポリシーを公開します。ボリュームが作成されると、それに関連付けられたQoSポリシーは、 `-o type=service_level`命名法。

Element ドライバーを使用して QoS サービス レベルを定義する最初の手順は、少なくとも 1 つのタイプを作成し、構成ファイル内の名前に関連付けられた最小 IOPS、最大 IOPS、およびバースト IOPS を指定することです。

その他の Element ソフトウェア ボリューム作成オプションは次のとおりです。

[cols="2*"]
|===
| オプション | 説明 


| `size`  a| 
ボリュームのサイズ。デフォルトは 1 GiB または構成エントリ...「defaults」: {"size": "5G"}。



| `blocksize`  a| 
512 または 4096 を使用します。デフォルトは 512 または構成エントリ DefaultBlockSize です。

|===


=== 例

QoS 定義を含む次のサンプル構成ファイルを参照してください。

[source, json]
----
{
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----
上記の構成には、Bronze、Silver、Gold の 3 つのポリシー定義があります。これらの名前は任意です。

* 10 GiB のゴールド ボリュームを作成します。
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 100 GiB の Bronze ボリュームを作成します。
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----

