---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: 'ボリュームを作成するには、標準の `docker volume`必要に応じてTridentドライバー名を指定したコマンド。' 
---
= ボリュームの操作
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
標準のボリューム作成、クローン作成、削除を簡単に行うことができます。 `docker volume`必要に応じてTridentドライバー名を指定したコマンド。



== ボリュームの作成

* デフォルト名を使用してドライバー付きのボリュームを作成します。
+
[source, console]
----
docker volume create -d netapp --name firstVolume
----
* 特定のTridentインスタンスでボリュームを作成します。
+
[source, console]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: 何も指定しない場合はlink:volume-driver-options.html["options"^]、ドライバーのデフォルトが使用されます。

* デフォルトのボリュームサイズを上書きします。ドライバーを使用して20 GiBのボリュームを作成するには、次の例を参照してください。
+
[source, console]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: ボリューム サイズは、オプションの単位 (例: 10G、20GB、3TiB) を持つ整数値を含む文字列として表されます。単位が指定されていない場合、デフォルトは G です。サイズの単位は、2 の累乗 (B、KiB、MiB、GiB、TiB) または 10 の累乗 (B、KB、MB、GB、TB) で表すことができます。省略単位には 2 の累乗を使用します (G = GiB、T = TiB、…)。





== ボリュームを削除する

* 他の Docker ボリュームと同じようにボリュームを削除します。
+
[source, console]
----
docker volume rm firstVolume
----
+

IMPORTANT: 使用する際は `solidfire-san`ドライバーの場合、上記の例ではボリュームを削除して消去します。



Trident for Docker をアップグレードするには、以下の手順を実行します。



== ボリュームをクローニングする

使用する際は `ontap-nas`、 `ontap-san` 、 `solidfire-san` 、 そして `gcp-cvs storage drivers`Trident はボリュームを複製できます。使用する際は `ontap-nas-flexgroup`または `ontap-nas-economy`ドライバーの場合、クローン作成はサポートされません。既存のボリュームから新しいボリュームを作成すると、新しいスナップショットが作成されます。

* ボリュームを検査してスナップショットを列挙します。
+
[source, console]
----
docker volume inspect <volume_name>
----
* 既存のボリュームから新しいボリュームを作成します。これにより、新しいスナップショットが作成されます。
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* ボリューム上の既存のスナップショットから新しいボリュームを作成します。これにより、新しいスナップショットは作成されません。
+
[source, console]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== 例

[source, console]
----
docker volume inspect firstVolume

[
  {
    "Driver": "ontap-nas",
    "Labels": null,
    "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
    "Name": "firstVolume",
    "Options": {},
    "Scope": "global",
    "Status": {
      "Snapshots": [
        {
          "Created": "2017-02-10T19:05:00Z",
          "Name": "hourly.2017-02-10_1505"
        }
      ]
    }
  }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== 外部で作成されたボリュームにアクセスする

外部で作成されたブロックデバイス（またはそのクローン）にTridentを使用するコンテナからアクセスできるのは、そのブロックデバイスにパーティションがなく、そのファイルシステムがTridentでサポートされている場合のみです（例： `ext4` -フォーマット済み `/dev/sdc1`Trident経由ではアクセスできなくなります)。
