---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: Trident は4 か月ごとにリリースされ、毎年 3 つのメジャー リリースが提供されます。新しいリリースはそれぞれ以前のリリースを基に構築されており、新しい機能やパフォーマンスの強化、バグ修正や改善が提供されます。  Tridentの新機能を活用するために、少なくとも年に 1 回はアップグレードすることをお勧めします。 
---
= Tridentをアップグレード
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
24.02 リリース以降、 Trident は4 か月ごとにリリースされ、毎年 3 つのメジャー リリースが提供されます。新しいリリースはそれぞれ以前のリリースに基づいて構築され、新しい機能、パフォーマンスの強化、バグ修正、改善が提供されます。  Tridentの新機能を活用できるよう、少なくとも年に 1 回はアップグレードすることをお勧めします。



== アップグレード前の考慮事項

Tridentの最新リリースにアップグレードする場合は、次の点を考慮してください。

* 特定の Kubernetes クラスター内のすべての名前空間にわたって、 Tridentインスタンスが 1 つだけインストールされている必要があります。
* Trident 23.07 以降では、v1 ボリューム スナップショットが必須となり、アルファ スナップショットやベータ スナップショットはサポートされなくなりました。
* Google CloudのCloud Volumes Serviceをlink:../trident-use/gcp.html#learn-about-trident-support-for-cloud-volumes-service-for-google-cloud["CVSサービスタイプ"]バックエンド構成を更新して、 `standardsw`または `zoneredundantstandardsw`Trident 23.01 からアップグレードする場合のサービス レベル。更新に失敗した `serviceLevel`バックエンドでボリュームが失敗する可能性があります。参照 link:../trident-use/gcp.html#cvs-service-type-examples["CVS サービスタイプのサンプル"] 詳細については。
* アップグレードする際には、 `parameter.fsType`で `StorageClasses`Tridentによって使用されます。削除して再作成できます `StorageClasses`既存のボリュームを中断することなく。
+
** これは、強制するための**要件**です https://kubernetes.io/docs/tasks/configure-pod-container/security-context/["セキュリティコンテキスト"^]SAN ボリューム用。
** https://github.com/NetApp/trident/tree/master/trident-installer/sample-input[sample input^]ディレクトリには、https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-basic.yaml.templなどの例が含まれています。[`storage-class-basic.yaml.templ` ^]とリンク:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml` ^]。
** 詳細については、link:../trident-rn.html["既知の問題"] 。






== ステップ1: バージョンを選択する

Tridentのバージョンは日付ベース `YY.MM`命名規則。「YY」は年の最後の 2 桁、「MM」は月です。ドットリリースは `YY.MM.X`規則では、「X」はパッチ レベルです。アップグレード元のバージョンに基づいて、アップグレード後のバージョンを選択します。

* インストールされているバージョンから 4 リリース以内の任意のターゲット リリースへの直接アップグレードを実行できます。たとえば、24.06 (または任意の 24.06 ドット リリース) から 25.06 に直接アップグレードできます。
* 4つのリリース期間外のリリースからアップグレードする場合は、複数ステップのアップグレードを実行してください。アップグレード元のバージョンに対応するアップグレード手順に従って、4つのリリース期間内に収まる最新リリースにアップグレードしてください。例えば、23.07 を実行していて、25.06 にアップグレードしたい場合（：）
+
.. 23.07 から 24.06 への最初のアップグレード。
.. 次に、24.06 から 25.06 にアップグレードします。





NOTE: OpenShift Container Platform でTridentオペレーターを使用してアップグレードする場合は、 Trident 21.01.1 以降にアップグレードする必要があります。 21.01.0 でリリースされたTridentオペレーターには既知の問題が含まれていますが、21.01.1 で修正されています。詳細については、 https://github.com/NetApp/trident/issues/517["GitHub上の問題の詳細"^] 。



== ステップ2: 元のインストール方法を決定する

最初にTrident をインストールする際に使用したバージョンを確認するには:

. 使用 `kubectl get pods -n trident`ポッドを検査します。
+
** オペレーターポッドがない場合、Tridentは次のようにインストールされます。 `tridentctl` 。
** オペレーター ポッドがある場合、 Trident は手動または Helm を使用してTridentオペレーターを使用してインストールされました。


. オペレーターポッドがある場合は、 `kubectl describe torc` Trident がHelm を使用してインストールされているかどうかを判断します。
+
** Helm ラベルがある場合、 Trident はHelm を使用してインストールされました。
** Helm ラベルがない場合、 Trident はTridentオペレーターを使用して手動でインストールされています。






== ステップ3: アップグレード方法を選択する

通常は、最初のインストールと同じ方法でアップグレードする必要がありますが、link:../trident-install/kubernetes-deploy.html#moving-between-installation-methods["インストール方法を切り替える"]。Trident をアップグレードするには 2 つのオプションがあります。

* link:upgrade-operator.html["Tridentオペレーターを使用してアップグレードする"]
+

TIP: 確認することをお勧めしますlink:upgrade-operator-overview.html["オペレーターのアップグレードワークフローを理解する"]オペレータにアップグレードする前に。

* 

