---
sidebar: sidebar 
permalink: trident-use/backend_ops_tridentctl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, tridentctl, create backends, delete backends, view backends, update backends 
summary: 'バックエンド管理操作を実行する方法について学習します。 `tridentctl` 。' 
---
= tridentctl でバックエンド管理を実行する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
バックエンド管理操作を実行する方法について学習します。 `tridentctl` 。



== バックエンドを作成する

作成後link:backends.html["バックエンド設定ファイル"^]、次のコマンドを実行します。

[listing]
----
tridentctl create backend -f <backend-file> -n trident
----
バックエンドの作成に失敗した場合は、バックエンドの構成に問題があります。次のコマンドを実行すると、ログを表示して原因を特定できます。

[listing]
----
tridentctl logs -n trident
----
設定ファイルの問題を特定して修正したら、 `create`再度コマンドを実行します。



== バックエンドを削除する

Tridentからバックエンドを削除するには、次の手順を実行します。

. バックエンド名を取得します。
+
[listing]
----
tridentctl get backend -n trident
----
. バックエンドを削除します。
+
[listing]
----
tridentctl delete backend <backend-name> -n trident
----



NOTE: Trident がこのバックエンドからプロビジョニングしたボリュームとスナップショットがまだ存在する場合、バックエンドを削除すると、新しいボリュームがプロビジョニングされなくなります。バックエンドは「削除中」の状態で存在し続けます。



== 既存のバックエンドを表示する

Trident が認識しているバックエンドを表示するには、次の手順を実行します。

* 概要を取得するには、次のコマンドを実行します。
+
[listing]
----
tridentctl get backend -n trident
----
* すべての詳細を取得するには、次のコマンドを実行します。
+
[listing]
----
tridentctl get backend -o json -n trident
----




== バックエンドを更新する

新しいバックエンド構成ファイルを作成したら、次のコマンドを実行します。

[listing]
----
tridentctl update backend <backend-name> -f <backend-file> -n trident
----
バックエンドの更新が失敗した場合は、バックエンドの構成に問題があるか、無効な更新を試行しました。次のコマンドを実行すると、ログを表示して原因を特定できます。

[listing]
----
tridentctl logs -n trident
----
設定ファイルの問題を特定して修正したら、 `update`再度コマンドを実行します。



== バックエンドを使用するストレージクラスを識別する

これはJSONで答えられる質問の例です。 `tridentctl`バックエンド オブジェクトの出力。これは、 `jq`インストールする必要があるユーティリティ。

[listing]
----
tridentctl get backend -o json | jq '[.items[] | {backend: .name, storageClasses: [.storage[].storageClasses]|unique}]'
----
これは、以下を使用して作成されたバックエンドにも適用されます。 `TridentBackendConfig` 。
