---
sidebar: sidebar 
permalink: trident-use/create-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: Kubernetes StorageClass ファイルを設計し、StorageClass を作成して、 Trident にボリュームのプロビジョニング方法を指示できます。 
---
= ストレージクラスを作成する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Kubernetes StorageClass オブジェクトを構成し、ボリュームのプロビジョニング方法をTrident に指示するストレージ クラスを作成します。



[[configure-a-kubernetes-storageclass-object]]
== Kubernetes StorageClassオブジェクトを構成する

その https://kubernetes.io/docs/concepts/storage/storage-classes/["Kubernetes StorageClassオブジェクト"^]そのクラスに使用されるプロビジョナーとしてTrident を識別し、ボリュームをプロビジョニングする方法をTrident に指示します。例えば：

[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-gold
provisioner: csi.trident.netapp.io
mountOptions:
  - nfsvers=3
  - nolock
parameters:
  backendType: "ontap-nas"
  media: "ssd"
allowVolumeExpansion: true
volumeBindingMode: Immediate
----
参照link:../trident-reference/objects.html["KubernetesとTridentオブジェクト"]ストレージクラスがどのように相互作用するかの詳細については、 `PersistentVolumeClaim` Trident がボリュームをプロビジョニングする方法を制御するためのパラメータ。



[[create-a-storage-class]]
== ストレージクラスを作成する

StorageClass オブジェクトを作成したら、ストレージ クラスを作成できます。<<ストレージクラスのサンプル>>使用したり変更したりできるいくつかの基本的なサンプルを提供します。

.手順
. これはKubernetesオブジェクトなので、 `kubectl` Kubernetes で作成します。
+
[listing]
----
kubectl create -f sample-input/storage-class-basic-csi.yaml
----
. これで、Kubernetes とTridentの両方に *basic-csi* ストレージ クラスが表示され、 Trident はバックエンドでプールを検出しているはずです。
+
[source, console]
----
kubectl get sc basic-csi
----


[listing]
----
NAME         PROVISIONER             AGE
basic-csi    csi.trident.netapp.io   15h
----
[source, console]
----
./tridentctl -n trident get storageclass basic-csi -o json
----
[source, json]
----
{
  "items": [
    {
      "Config": {
        "version": "1",
        "name": "basic-csi",
        "attributes": {
          "backendType": "ontap-nas"
        },
        "storagePools": null,
        "additionalStoragePools": null
      },
      "storage": {
        "ontapnas_10.0.0.1": [
          "aggr1",
          "aggr2",
          "aggr3",
          "aggr4"
        ]
      }
    }
  ]
}
----


[[storage-class-samples]]
=== ストレージクラスのサンプル

Tridentは https://github.com/NetApp/trident/tree/master/trident-installer/sample-input/storage-class-samples["特定のバックエンド向けのシンプルなストレージクラス定義"^]。

あるいは、編集することもできます `sample-input/storage-class-csi.yaml.templ`インストーラーに付属のファイルと置き換えます `__BACKEND_TYPE__`ストレージ ドライバー名を使用します。

[listing]
----
./tridentctl -n trident get backend
+-------------+----------------+--------------------------------------+--------+---------+
|    NAME     | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------+----------------+--------------------------------------+--------+---------+
| nas-backend | ontap-nas      | 98e19b74-aec7-4a3d-8dcf-128e5033b214 | online |       0 |
+-------------+----------------+--------------------------------------+--------+---------+

cp sample-input/storage-class-csi.yaml.templ sample-input/storage-class-basic-csi.yaml

# Modify __BACKEND_TYPE__ with the storage driver field above (e.g., ontap-nas)
vi sample-input/storage-class-basic-csi.yaml
----