---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: ONTAP NAS ドライバーを使用してONTAPバックエンドを構成する方法について学習します。 
---
= ONTAP NAS ドライバーの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPおよびCloud Volumes ONTAP NAS ドライバーを使用してONTAPバックエンドを構成する方法について学習します。



[[ontap-nas-driver-details]]
== ONTAP NAS ドライバーの詳細

Trident は、 ONTAPクラスタと通信するための次の NAS ストレージ ドライバーを提供します。サポートされているアクセス モードは、_ReadWriteOnce_ (RWO)、_ReadOnlyMany_ (ROX)、_ReadWriteMany_ (RWX)、_ReadWriteOncePod_ (RWOP) です。

[cols="2, 1, 1, 2, 2"]
|===
| ドライバ | プロトコル | ボリュームモード | サポートされているアクセスモード | サポートされているファイルシステム 


| `ontap-nas`  a| 
NFS SMB
 a| 
Filesystem
 a| 
RWO、ROX、RWX、RWOP
 a| 
"", `nfs` 、 `smb`



| `ontap-nas-economy`  a| 
NFS SMB
 a| 
Filesystem
 a| 
RWO、ROX、RWX、RWOP
 a| 
"", `nfs` 、 `smb`



| `ontap-nas-flexgroup`  a| 
NFS SMB
 a| 
Filesystem
 a| 
RWO、ROX、RWX、RWOP
 a| 
"", `nfs` 、 `smb`

|===
[WARNING]
====
* 使用 `ontap-san-economy`永続ボリュームの使用数がlink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされているONTAPボリュームの制限"^]。
* 使用 `ontap-nas-economy`永続ボリュームの使用数がlink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされているONTAPボリュームの制限"^]そして `ontap-san-economy`ドライバーは使用できません。
* 使用しないでください `ontap-nas-economy`データ保護、災害復旧、モビリティの必要性が予想される場合。
* NetApp、ontap-san を除くすべてのONTAPドライバーで Flexvol autogrow を使用することは推奨されていません。回避策として、 Trident はスナップショット リザーブの使用をサポートし、それに応じて Flexvol ボリュームを拡張します。


====


[[user-permissions]]
== ユーザー権限

Tridentは、通常、 ONTAPまたはSVM管理者として実行することを想定しています。 `admin`クラスターユーザーまたは `vsadmin`SVM ユーザー、または同じロールを持つ別の名前のユーザー。

Amazon FSx for NetApp ONTAPの導入では、 Tridentはクラスタを使用してONTAPまたはSVM管理者として実行されることが想定されています。 `fsxadmin`ユーザーまたは `vsadmin`SVM ユーザー、または同じロールを持つ別の名前のユーザー。その `fsxadmin`ユーザーは、クラスター管理者ユーザーの限定的な代替です。


NOTE: を使用する場合 `limitAggregateUsage`パラメータには、クラスター管理者の権限が必要です。 Amazon FSx for NetApp ONTAPをTridentで使用する場合、 `limitAggregateUsage`パラメータは、 `vsadmin`そして `fsxadmin`ユーザーアカウント。このパラメータを指定すると、構成操作は失敗します。

ONTAP内でTridentドライバーが使用できる、より制限の厳しいロールを作成することは可能ですが、お勧めしません。  Tridentのほとんどの新しいリリースでは、考慮する必要がある追加の API が呼び出されるため、アップグレードが困難になり、エラーが発生しやすくなります。
