---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Trident をAmazon FSx for NetApp ONTAPと併用することで、Amazon Elastic Kubernetes Service (EKS) で実行されている Kubernetes クラスターがONTAPによってサポートされるブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。' 
---
= Amazon FSx for NetApp ONTAPでTrident を使用する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^]は、 NetApp ONTAPストレージ オペレーティング システムを搭載したファイル システムを起動および実行できるようにする、完全に管理された AWS サービスです。  FSx for ONTAP を使用すると、使い慣れたNetApp の機能、パフォーマンス、管理機能を活用しながら、AWS にデータを保存するシンプルさ、俊敏性、セキュリティ、スケーラビリティを活用できます。  FSx for ONTAP は、 ONTAPファイル システム機能と管理 API をサポートしています。

Amazon FSx for NetApp ONTAPファイルシステムをTridentと統合して、Amazon Elastic Kubernetes Service (EKS) で実行されている Kubernetes クラスターがONTAPによってサポートされるブロックおよびファイルの永続ボリュームをプロビジョニングできるようにすることができます。

ファイルシステムは、オンプレミスのONTAPクラスターに類似した、 Amazon FSxの主要なリソースです。各 SVM 内に、ファイル システム内のファイルとフォルダーを保存するデータ コンテナーであるボリュームを 1 つまたは複数のボリュームを作成できます。 Amazon FSx for NetApp ONTAP はクラウド内のマネージド ファイル システムとして提供されます。新しいファイル システム タイプは * NetApp ONTAP* と呼ばれます。

Trident をAmazon FSx for NetApp ONTAPと併用することで、Amazon Elastic Kubernetes Service (EKS) で実行されている Kubernetes クラスターがONTAPによってサポートされるブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。



== 要件

に加えてlink:../trident-get-started/requirements.html["Tridentの要件"]FSx for ONTAP をTridentと統合するには、次のものが必要です。

* 既存のAmazon EKSクラスターまたはセルフマネージドKubernetesクラスターで `kubectl`インストールされました。
* クラスターのワーカーノードからアクセスできる既存のAmazon FSx for NetApp ONTAPファイルシステムとストレージ仮想マシン (SVM)。
* 準備されたワーカーノードlink:worker-node-prep.html["NFS または iSCSI"]。
+

NOTE: Amazon LinuxおよびUbuntuに必要なノード準備手順に従ってください。 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon マシンイメージ"^] (AMI) は EKS AMI タイプによって異なります。





== 考慮事項

* SMB ボリューム:
+
** SMBボリュームは、 `ontap-nas`ドライバーのみ。
** SMB ボリュームはTrident EKS アドオンではサポートされていません。
** Trident は、 Windows ノードで実行されているポッドにマウントされた SMB ボリュームのみをサポートします。参照 link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["SMBボリュームのプロビジョニングの準備"] 詳細については。


* Trident 24.02 より前では、自動バックアップが有効になっているAmazon FSxファイルシステムで作成されたボリュームは、 Tridentでは削除できませんでした。  Trident 24.02以降でこの問題を回避するには、 `fsxFilesystemID` 、AWS `apiRegion` 、AWS `apikey` 、AWS `secretKey` AWS FSx for ONTAPのバックエンド構成ファイル内。
+

NOTE: TridentにIAMロールを指定する場合は、 `apiRegion` 、 `apiKey` 、 そして `secretKey`フィールドをTridentに明示的に渡します。詳細については、link:../trident-use/trident-fsx-examples.html["FSx for ONTAP の構成オプションと例"] 。





=== Trident SAN/iSCSI と EBS-CSI ドライバーの同時使用

AWS (EKS、ROSA、EC2、またはその他のインスタンス) で ontap-san ドライバー (iSCSI など) を使用する予定の場合、ノードに必要なマルチパス構成が Amazon Elastic Block Store (EBS) CSI ドライバーと競合する可能性があります。同じノード上の EBS ディスクに干渉せずにマルチパスが機能することを保証するには、マルチパス設定で EBS を除外する必要があります。この例では、 `multipath.conf` EBS ディスクをマルチパスから除外しながら必要なTrident設定を含むファイル:

[listing]
----
defaults {
    find_multipaths no
}
blacklist {
    device {
        vendor "NVME"
        product "Amazon Elastic Block Store"
    }
}
----


== 認証

Trident は2 つの認証モードを提供します。

* 認証情報ベース (推奨): 認証情報を AWS Secrets Manager に安全に保存します。使用することができます `fsxadmin`ファイルシステムのユーザーまたは `vsadmin`SVM 用に構成されたユーザー。
+

WARNING: Tridentは、 `vsadmin` SVM ユーザーとして、または同じロールを持つ別の名前のユーザーとして。 Amazon FSx for NetApp ONTAPには `fsxadmin`ONTAPの限定的な代替品であるユーザー `admin`クラスター ユーザー。強くお勧めします `vsadmin`Trident付き。

* 証明書ベース: Trident は、 SVM にインストールされた証明書を使用して、FSx ファイル システム上の SVM と通信します。


認証を有効にする方法の詳細については、ドライバー タイプの認証を参照してください。

* link:ontap-nas-prep.html["ONTAP NAS認証"]
* link:ontap-san-prep.html["ONTAP SAN認証"]




== テスト済みの Amazon マシンイメージ (AMI)

EKS クラスターはさまざまなオペレーティングシステムをサポートしていますが、AWS は特定の Amazon マシンイメージ (AMI) をコンテナと EKS 用に最適化しています。次の AMI はNetApp Trident 25.02 でテストされています。

|===


| アミ | NAS | NAS-エコノミー | iSCSI | iSCSIエコノミー 


| AL2023_x86_64_標準 | はい | はい | はい | はい 


| AL2_x86_64 | はい | はい | ○* | ○* 


| ボトルロケット_x86_64 | はい** | はい | 該当なし | 該当なし 


| AL2023_ARM_64_標準 | はい | はい | はい | はい 


| AL2_ARM_64 | はい | はい | ○* | ○* 


| ボトルロケットアーム64 | はい** | はい | 該当なし | 該当なし 
|===
* * ノードを再起動せずにPVを削除することはできません
* ** Tridentバージョン 25.02 の NFSv3 では動作しません。



NOTE: 必要な AMI がここにリストされていない場合、それはサポートされていないという意味ではなく、単にテストされていないという意味です。このリストは、動作することがわかっている AMI のガイドとして機能します。

*テストに使用したデバイス*:

* EKS version: 1.32
* インストール方法: Helm 25.06 および AWS アドオン 25.06
* NAS については、NFSv3 と NFSv4.1 の両方がテストされました。
* SAN の場合、NVMe-oF ではなく iSCSI のみがテストされました。


*実行されたテスト*:

* 作成: ストレージクラス、PVC、ポッド
* 削除: ポッド、PVC (通常、qtree/lun - エコノミー、AWS バックアップ付き NAS)




== 詳細情報の参照

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAPドキュメント"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Amazon FSx for NetApp ONTAPに関するブログ投稿"^]

