---
sidebar: sidebar 
permalink: trident-use/vol-provision.html 
keywords: volumes, pvc, pv, persistentvolume, persistentvolumeclaim, mount, pod, provision 
summary: '構成された Kubernetes StorageClass を使用して PV へのアクセスを要求する PersistentVolume (PV) と PersistentVolumeClaim (PVC) を作成します。その後、PV をポッドにマウントできます。' 
---
= ボリュームをプロビジョニングする
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
構成された Kubernetes StorageClass を使用して PV へのアクセスを要求する PersistentVolumeClaim (PVC) を作成します。その後、PV をポッドにマウントできます。



== 概要

あ https://kubernetes.io/docs/concepts/storage/persistent-volumes["_永続ボリュームクレーム_"^](PVC) は、クラスター上の PersistentVolume へのアクセス要求です。

PVC は、特定のサイズまたはアクセス モードのストレージを要求するように構成できます。関連付けられた StorageClass を使用すると、クラスター管理者は PersistentVolume のサイズやアクセス モードだけでなく、パフォーマンスやサービス レベルなどの制御も行えます。

PVC を作成したら、ボリュームをポッドにマウントできます。



== PVCを作成する

.手順
. PVCを作成
+
[listing]
----
kubectl create -f pvc.yaml
----
. PVC ステータスを確認します。
+
[listing]
----
kubectl get pvc
----


[listing]
----
NAME        STATUS  VOLUME     CAPACITY   ACCESS MODES  STORAGECLASS AGE
pvc-storage Bound   pv-name    1Gi        RWO                  5m
----
. ボリュームをポッドにマウントします。
+
[listing]
----
kubectl create -f pv-pod.yaml
----
+

NOTE: 進捗状況は以下で確認できます。 `kubectl get pod --watch` 。

. ボリュームがマウントされていることを確認する `/my/mount/path`。
+
[listing]
----
kubectl exec -it task-pv-pod -- df -h /my/mount/path
----
. これでポッドを削除できます。  Pod アプリケーションは存在しなくなりますが、ボリュームは残ります。
+
[listing]
----
kubectl delete pod pv-pod
----




=== サンプルマニフェスト

.PersistentVolumeClaim サンプルマニフェスト
[%collapsible]
====
これらの例は、基本的な PVC 構成オプションを示しています。

.RWO アクセス付き PVC
この例では、RWOアクセスを持つ基本的なPVCが、StorageClassに関連付けられています。 `basic-csi` 。

[source, yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
.NVMe/TCP を使用した PVC
この例では、RWOアクセスを持つNVMe/TCPの基本的なPVCを示しており、これはStorageClassに関連付けられています。 `protection-gold` 。

[source, yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san-nvme
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 300Mi
storageClassName: protection-gold
----
====
.ポッドマニフェストのサンプル
[%collapsible]
====
これらの例は、PVC をポッドに接続するための基本的な構成を示しています。

.基本設定
[source, yaml]
----
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
       claimName: pvc-storage
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: storage
----
.基本的なNVMe/TCP構成
[source, yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  volumes:
    - name: basic-pvc
      persistentVolumeClaim:
        claimName: pvc-san-nvme
  containers:
    - name: task-pv-container
      image: nginx
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: basic-pvc
----
====
参照link:../trident-reference/objects.html["KubernetesとTridentオブジェクト"]ストレージクラスがどのように相互作用するかの詳細については、 `PersistentVolumeClaim` Trident がボリュームをプロビジョニングする方法を制御するためのパラメータ。
