---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Trident をインストールする前に、これらの一般的なシステム要件を確認する必要があります。特定のバックエンドには追加の要件がある場合があります。 
---
= 要件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident をインストールする前に、これらの一般的なシステム要件を確認する必要があります。特定のバックエンドには追加の要件がある場合があります。



[[critical-information-about-trident]]
== Tridentに関する重要な情報

* Tridentに関する以下の重要な情報を必ずお読みください。*

.<strong>Tridentに関する重要な情報</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 がTridentでサポートされるようになりました。Kubernetes をアップグレードする前にTridentをアップグレードします。
* TridentはSAN環境でのマルチパス構成の使用を厳格に強制しており、推奨値は `find_multipaths: no`multipath.conf ファイル内。
+
非マルチパス構成の使用または `find_multipaths: yes`または `find_multipaths: smart`multipath.conf ファイルの値が小さいとマウントが失敗します。Tridentは、 `find_multipaths: no` 21.07 リリース以降。



=====
====


[[supported-frontends-orchestrators]]
== サポートされているフロントエンド（オーケストレーター）

Trident は、次のような複数のコンテナ エンジンとオーケストレーターをサポートしています。

* Anthos On-Prem (VMware) とベアメタル版 Anthos 1.16
* Kubernetes 1.27 - 1.34
* OpenShift 4.12、4.14 - 4.19 (OpenShift 4.19 で iSCSI ノードの準備を使用する場合、サポートされる最小Tridentバージョンは 25.06.1 です。)
+

NOTE: Tridentは、 OpenShiftの古いバージョンを引き続きサポートします。link:https://access.redhat.com/support/policy/updates/openshift["Red Hat 延長アップデートサポート (EUS) リリースライフサイクル"]アップストリームで公式にサポートされなくなった Kubernetes バージョンに依存している場合でも同様です。このような場合、 Tridentをインストールするときに、Kubernetes バージョンに関する警告メッセージは無視しても問題ありません。

* Rancher Kubernetes Engine 2 (RKE2) v1.27.x - 1.34.x
+

NOTE: Tridentは Rancher Kubernetes Engine 2 (RKE2) バージョン 1.27.x - 1.34.x でサポートされていますが、 Tridentは現在 RKE2 v1.28.5+rke2r1 でのみ認定されています。_



Trident は、Google Kubernetes Engine (GKE)、Amazon Elastic Kubernetes Services (EKS)、Azure Kubernetes Service (AKS)、Mirantis Kubernetes Engine (MKE)、VMWare Tanzu Portfolio など、他の多くの完全マネージド型およびセルフマネージド型の Kubernetes サービスとも連携します。

TridentとONTAPは、以下のストレージプロバイダーとして使用できます。link:https://kubevirt.io/["キューブバート"] 。


WARNING: TridentがインストールされているKubernetesクラスタを1.25から1.26以降にアップグレードする前に、link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Helmインストールのアップグレード"] 。



[[supported-backends-storage]]
== サポートされているバックエンド（ストレージ）

Trident を使用するには、サポートされている以下のバックエンドの 1 つ以上が必要です。

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp Volumes
* NetAppオール SAN アレイ (ASA)
* オンプレミスFAS、AFF、またはASA r2（iSCSI、NVMe/TCP、FC）で、NetAppの完全サポートまたは限定サポート対象のONTAPバージョンを実行しているもの。link:https://mysupport.netapp.com/site/info/version-support["ソフトウェア バージョンのサポート"]を参照してください。
* NetApp HCI/Element ソフトウェア 11 以上




[[trident-support-for-kubevirt-and-openshift-virtualization]]
== KubeVirt と OpenShift Virtualization のTridentサポート

.サポートされているストレージ ドライバー:
Trident は、 KubeVirt および OpenShift Virtualization 用の次のONTAPドライバーをサポートしています。

* オンタップナス
* オンタップナスエコノミー
* ontap-san (iSCSI、FCP、NVMe over TCP)
* ontap-san-economy (iSCSI のみ)


.考慮すべき点:
* ストレージクラスを更新して、 `fsType`パラメータ（例： `fsType: "ext4"` ) を OpenShift Virtualization 環境で実行します。必要に応じて、ボリュームモードを明示的にブロックに設定します。 `volumeMode=Block`パラメータの `dataVolumeTemplates`CDI にブロック データ ボリュームを作成するように通知します。
* _ブロック ストレージ ドライバーの RWX アクセス モード_: ontap-san (iSCSI、NVMe/TCP、FC) および ontap-san-economy (iSCSI) ドライバーは、"volumeMode: Block" (raw デバイス) でのみサポートされます。これらのドライバーにとって、 `fstype`ボリュームが RAW デバイス モードで提供されているため、このパラメータは使用できません。
* RWX アクセス モードが必要なライブ移行ワークフローでは、次の組み合わせがサポートされています。
+
** NFS + `volumeMode=Filesystem`
** iSCSI + `volumeMode=Block` （rawデバイス）
** NVMe/TCP + `volumeMode=Block` （rawデバイス）
** FC + `volumeMode=Block` （rawデバイス）






[[feature-requirements]]
== 機能の要件

以下の表は、このリリースのTridentで利用できる機能と、それがサポートする Kubernetes のバージョンをまとめたものです。

[cols="3"]
|===
| 特徴 | Kubernetesバージョン | 機能ゲートが必要ですか? 


| Trident  a| 
1.27 - 1.34
 a| 
いいえ



| ボリューム Snapshot  a| 
1.27 - 1.34
 a| 
いいえ



| ボリュームスナップショットからのPVC  a| 
1.27 - 1.34
 a| 
いいえ



| iSCSI PV のサイズ変更  a| 
1.27 - 1.34
 a| 
いいえ



| ONTAP双方向 CHAP  a| 
1.27 - 1.34
 a| 
いいえ



| 動的エクスポートポリシー  a| 
1.27 - 1.34
 a| 
いいえ



| Tridentオペレーター  a| 
1.27 - 1.34
 a| 
いいえ



| CSIトポロジ  a| 
1.27 - 1.34
 a| 
いいえ

|===


[[tested-host-operating-systems]]
== テスト済みのホストオペレーティングシステム

Trident は特定のオペレーティング システムを公式にはサポートしていませんが、次のオペレーティング システムは動作することが分かっています。

* AMD64 および ARM64 上の OpenShift Container Platform でサポートされる Red Hat Enterprise Linux CoreOS (RHCOS) バージョン
* AMD64 および ARM64 上の Red Hat Enterprise Linux (RHEL) 8 以降
+

NOTE: NVMe/TCP には RHEL 9 以降が必要です。

* AMD64およびARM64上のUbuntu 22.04 LTS以降
* Windows Server 2022
* SUSE Linux Enterprise Server (SLES) 15 以降


デフォルトでは、 Trident はコンテナ内で実行されるため、どの Linux ワーカーでも実行されます。ただし、これらのワーカーは、使用しているバックエンドに応じて、標準の NFS クライアントまたは iSCSI イニシエーターを使用してTrident が提供するボリュームをマウントできる必要があります。

その `tridentctl`このユーティリティは、これらの Linux ディストリビューションのいずれでも実行できます。



[[host-configuration]]
== ホスト構成

Kubernetes クラスター内のすべてのワーカーノードは、ポッド用にプロビジョニングしたボリュームをマウントできる必要があります。ワーカーノードを準備するには、ドライバーの選択に基づいて NFS、iSCSI、または NVMe ツールをインストールする必要があります。

link:../trident-use/worker-node-prep.html["ワーカーノードを準備する"]



[[storage-system-configuration]]
== ストレージシステムの構成

Trident、バックエンド構成で使用できるようになる前に、ストレージ システムの変更が必要になる場合があります。

link:../trident-use/backends.html["バックエンドを構成する"]



[[trident-ports]]
== Tridentポート

Trident は通信のために特定のポートにアクセスする必要があります。

link:../trident-reference/ports.html["Tridentポート"]



[[container-images-and-corresponding-kubernetes-versions]]
== コンテナイメージと対応するKubernetesバージョン

エアギャップ インストールの場合、次のリストはTrident をインストールするために必要なコンテナー イメージのリファレンスです。使用 `tridentctl images`必要なコンテナ イメージのリストを確認するコマンド。



[[container-images-required-for-trident-25-06-2]]
=== Trident 25.06.2 に必要なコンテナ イメージ

[cols="2"]
|===
| Kubernetesのバージョン | コンテナイメージ 


| v1.27.0、v1.28.0、v1.29.0、v1.30.0、v1.31.0、v1.32.0、v1.33.0、v1.34.0  a| 
* docker.io/netapp/トライデント:25.06.2
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
* docker.io/netapp/trident-operator:25.06.2 (オプション)


|===


[[container-images-required-for-trident-25-06]]
=== Trident 25.06 に必要なコンテナ イメージ

[cols="2"]
|===
| Kubernetesのバージョン | コンテナイメージ 


| v1.27.0、v1.28.0、v1.29.0、v1.30.0、v1.31.0、v1.32.0、v1.33.0、v1.34.0  a| 
* docker.io/netapp/トライデント:25.06.0
* docker.io/netapp/trident-autosupport:25.06
* registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
* registry.k8s.io/sig-storage/csi-attacher:v4.8.1
* registry.k8s.io/sig-storage/csi-resizer:v1.13.2
* registry.k8s.io/sig-storage/csi-snapshotter:v8.2.1
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0
* docker.io/netapp/trident-operator:25.06.0 (オプション)


|===