---
sidebar: sidebar 
permalink: trident-concepts/snapshots.html 
keywords: provisioning, Trident 
summary: Trident がドライバーのボリューム スナップショットの作成をどのように処理するかについて詳しく説明します。 
---
= ボリュームスナップショット
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident がドライバーのボリューム スナップショットの作成をどのように処理するかについて詳しく説明します。



[[learn-about-volume-snapshot-creation]]
== ボリュームスナップショットの作成について学ぶ

* のために `ontap-nas`、 `ontap-san` 、 `gcp-cvs` 、 そして `azure-netapp-files`ドライバーごとに、各永続ボリューム (PV) がFlexVol volumeにマップされます。その結果、ボリューム スナップショットはNetAppスナップショットとして作成されます。 NetAppスナップショット テクノロジーは、競合するスナップショット テクノロジーよりも優れた安定性、拡張性、回復性、パフォーマンスを実現します。これらのスナップショット コピーは、作成に必要な時間とストレージ スペースの両方において非常に効率的です。
* のために `ontap-nas-flexgroup`ドライバーでは、各永続ボリューム (PV) がFlexGroupにマップされます。その結果、ボリューム スナップショットはNetApp FlexGroupスナップショットとして作成されます。 NetAppスナップショット テクノロジーは、競合するスナップショット テクノロジーよりも優れた安定性、拡張性、回復性、パフォーマンスを実現します。これらのスナップショット コピーは、作成に必要な時間とストレージ スペースの両方において非常に効率的です。
* のために `ontap-san-economy`ドライバーでは、PV は共有FlexVolボリューム上に作成された LUN にマップされます。PV の VolumeSnapshot は、関連付けられた LUN の FlexClone を実行することによって実現されます。 ONTAP FlexCloneテクノロジーにより、最大規模のデータセットであってもほぼ瞬時にコピーを作成できます。コピーは親とデータ ブロックを共有し、メタデータに必要なものを除いてストレージを消費しません。
* のために `solidfire-san`ドライバーにより、各 PV はNetApp Elementソフトウェア/ NetApp HCIクラスター上に作成された LUN にマッピングされます。 VolumeSnapshots は、基盤となる LUN の要素スナップショットによって表されます。これらのスナップショットはポイントインタイムコピーであり、システム リソースとスペースをわずかにしか消費しません。
* 作業する際は `ontap-nas`そして `ontap-san`ドライバーの場合、 ONTAPスナップショットはFlexVolのポイントインタイム コピーであり、 FlexVol自体のスペースを消費します。これにより、スナップショットが作成/スケジュールされるにつれて、ボリューム内の書き込み可能な領域の量が時間の経過とともに減少する可能性があります。これを解決する簡単な方法の 1 つは、Kubernetes を使用してサイズを変更し、ボリュームを増やすことです。もう 1 つのオプションは、不要になったスナップショットを削除することです。  Kubernetes を通じて作成された VolumeSnapshot が削除されると、 Trident は関連するONTAPスナップショットを削除します。  Kubernetes 経由で作成されなかったONTAPスナップショットも削除できます。


Tridentでは、VolumeSnapshots を使用してそこから新しい PV を作成できます。これらのスナップショットからの PV の作成は、サポートされているONTAPおよび CVS バックエンドのFlexCloneテクノロジーを使用して実行されます。スナップショットから PV を作成する場合、バックアップ ボリュームはスナップショットの親ボリュームのFlexCloneになります。その `solidfire-san`ドライバーは、Element ソフトウェア ボリューム クローンを使用してスナップショットから PV を作成します。ここでは、Element スナップショットからクローンを作成します。
