---
sidebar: sidebar 
permalink: trident-reco/integrate-trident.html 
keywords: kubernetes, clusters, nodes, components, master, compute, fsx, flexgroup, flexvolume, solidfire, hci, virtual pool, cvs, gcp, volumes 
summary: Kubernetes クラスターは通常、2 種類のノードで構成され、それぞれが異なる機能の側面を担当します。 
---
= Tridentを統合
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident を統合するには、ドライバーの選択とデプロイメント、ストレージ クラスの設計、仮想プールの設計、ストレージ プロビジョニングに対する Persistent Volume Claim (PVC) の影響、ボリューム操作、およびTrident を使用した OpenShift サービスのデプロイメントといった設計およびアーキテクチャ要素の統合が必要です。



== ドライバーの選択と展開

ストレージ システムのバックエンド ドライバーを選択して展開します。



=== ONTAPバックエンド ドライバー

ONTAPバックエンド ドライバーは、使用されるプロトコルと、ストレージ システム上でボリュームがプロビジョニングされる方法によって区別されます。したがって、どのドライバーを展開するかを決定する際には慎重に検討してください。

より高いレベルでは、アプリケーションに共有ストレージを必要とするコンポーネント (同じ PVC にアクセスする複数のポッド) がある場合、NAS ベースのドライバーがデフォルトの選択肢になりますが、ブロックベースの iSCSI ドライバーは非共有ストレージのニーズを満たします。アプリケーションの要件と、ストレージおよびインフラストラクチャ チームの快適度に基づいてプロトコルを選択します。一般的に言えば、ほとんどのアプリケーションではそれらの間にほとんど違いがないため、共有ストレージ (複数のポッドが同時にアクセスする必要がある場合) が必要かどうかに基づいて決定することがよくあります。

利用可能なONTAPバックエンド ドライバーは次のとおりです。

* `ontap-nas`: プロビジョニングされた各 PV は完全なONTAP FlexVolume です。
* `ontap-nas-economy`: プロビジョニングされる各 PV は qtree であり、FlexVolume ごとに設定可能な数の qtree があります (デフォルトは 200)。
* `ontap-nas-flexgroup`: 各 PV は完全なONTAP FlexGroupとしてプロビジョニングされ、SVM に割り当てられたすべてのアグリゲートが使用されます。
* `ontap-san`: プロビジョニングされた各 PV は、独自の FlexVolume 内の LUN です。
* `ontap-san-economy`: プロビジョニングされる各 PV は LUN であり、FlexVolume ごとに構成可能な数の LUN (デフォルトは 100) があります。


3 つの NAS ドライバーのいずれかを選択すると、アプリケーションで利用できる機能にいくつかの影響が生じます。

以下の表では、すべての機能がTridentを通じて公開されているわけではないことに注意してください。一部の機能は、その機能が必要な場合、プロビジョニング後にストレージ管理者が適用する必要があります。上付き脚注は、機能およびドライバーごとに機能を区別します。

[cols="20,10,10,10,10,10,10,10"]
|===
| ONTAP NAS ドライバー | Snapshot 数 | クローン | 動的エクスポートポリシー | マルチアタッチ | QoS | サイズ変更 | レプリケーション 


| `ontap-nas` | はい | はい | はい脚注:5[] | はい | はい脚注:1[] | はい | はい脚注:1[] 


| `ontap-nas-economy` | 脚注:3[] | 脚注:3[] | はい脚注:5[] | はい | 脚注:3[] | はい | 脚注:3[] 


| `ontap-nas-flexgroup` | はい脚注:1[] | いいえ | はい脚注:5[] | はい | はい脚注:1[] | はい | はい脚注:1[] 
|===
Trident はONTAP用の 2 つの SAN ドライバーを提供しており、その機能を以下に示します。

[cols="20,10,10,10,10,10,10,10"]
|===
| ONTAP SAN ドライバー | Snapshot 数 | クローン | マルチアタッチ | 双方向CHAP | QoS | サイズ変更 | レプリケーション 


| `ontap-san` | はい | はい | はい脚注:4[] | はい | はい脚注:1[] | はい | はい脚注:1[] 


| `ontap-san-economy` | はい | はい | はい脚注:4[] | はい | 脚注:3[] | はい | 脚注:3[] 
|===
[verse]
上記の表の脚注: はい脚注:1[]: Tridentによって管理されません はい脚注:2[]: Tridentによって管理されますが、PV 細分化されません いいえ脚注:3[]: Tridentによって管理されず、PV 細分化されません はい脚注:4[]: 生のブロック ボリュームでサポートされます はい脚注:5[]: Tridentによってサポートされます

PV 粒度ではない機能は FlexVolume 全体に適用され、すべての PV (つまり、共有 FlexVol 内の qtree または LUN) が共通のスケジュールを共有します。

上の表からわかるように、 `ontap-nas`そして `ontap-nas-economy`同じです。しかし、 `ontap-nas-economy`ドライバーは PV 単位の粒度でスケジュールを制御する機能を制限します。これは特に災害復旧とバックアップ計画に影響を与える可能性があります。  ONTAPストレージでPVCクローン機能を活用したい開発チームにとって、これは `ontap-nas`、 `ontap-san`または `ontap-san-economy`ドライバー。


NOTE: その `solidfire-san`ドライバーは PVC の複製も可能です。



=== Cloud Volumes ONTAPバックエンド ドライバー

Cloud Volumes ONTAP は、ファイル共有や、NAS および SAN プロトコル (NFS、SMB/CIFS、iSCSI) を提供するブロック レベルのストレージなど、さまざまなユース ケースに対応するエンタープライズ クラスのストレージ機能とともにデータ制御を提供します。 Cloud Volume ONTAPと互換性のあるドライバーは `ontap-nas`、 `ontap-nas-economy` 、 `ontap-san`そして `ontap-san-economy`。これらは、Cloud Volume ONTAP for Azure、Cloud Volume ONTAP for GCP に適用されます。



=== Amazon FSx for ONTAPバックエンドドライバー

Amazon FSx for NetApp ONTAPすると、使い慣れたNetApp の機能、パフォーマンス、管理機能を活用しながら、AWS にデータを保存するシンプルさ、俊敏性、セキュリティ、スケーラビリティを活用できます。  FSx for ONTAP は、多くのONTAPファイル システム機能と管理 API をサポートしています。  Cloud Volume ONTAPと互換性のあるドライバーは `ontap-nas`、 `ontap-nas-economy` 、 `ontap-nas-flexgroup` 、 `ontap-san`そして `ontap-san-economy`。



=== NetApp HCI/ SolidFireバックエンド ドライバー

その `solidfire-san`NetApp HCI/ SolidFireプラットフォームで使用されるドライバーは、管理者が QoS 制限に基づいてTridentの Element バックエンドを構成するのに役立ちます。 Tridentによってプロビジョニングされたボリュームに特定の QoS 制限を設定するようにバックエンドを設計する場合は、 `type`バックエンド ファイルのパラメータ。管理者は、ストレージ上に作成できるボリュームサイズを制限することもできます。 `limitVolumeSize`パラメータ。現在、ボリュームのサイズ変更やボリュームの複製などのElementストレージ機能は、 `solidfire-san`ドライバ。これらの操作は、Element Software Web UI を通じて手動で実行する必要があります。

[cols="20,10,10,10,10,10,10,10"]
|===
| SolidFireドライバー | Snapshot 数 | クローン | マルチアタッチ | チャップ | QoS | サイズ変更 | レプリケーション 


| `solidfire-san` | はい | はい | はい脚注:2[] | はい | はい | はい | はい脚注:1[] 
|===
[verse]
脚注: はい脚注:1[]: Tridentでは管理されません はい脚注:2[]: raw ブロックボリュームでサポートされます



=== Azure NetApp Filesバックエンド ドライバー

Tridentは `azure-netapp-files`ドライバーを使用してlink:https://azure.microsoft.com/en-us/products/netapp/["Azure NetApp Files"^]サービスを管理します。

このドライバの詳細と設定方法については、link:https://docs.netapp.com/us-en/trident/trident-use/anf.html["Azure NetApp FilesのTridentバックエンド構成"^] 。

[cols="20,10,10,10,10,10,10"]
|===
| Azure NetApp Filesドライバー | Snapshot 数 | クローン | マルチアタッチ | QoS | 拡張 | レプリケーション 


| `azure-netapp-files` | はい | はい | はい | はい | はい | はい脚注:1[] 
|===
[verse]
脚注: はい脚注:1[]:Tridentによって管理されていない



=== Google Cloud バックエンド ドライバー上のCloud Volumes Service

Tridentは `gcp-cvs`Google Cloud 上のCloud Volumes Serviceにリンクするためのドライバー。

その `gcp-cvs`ドライバーは仮想プールを使用してバックエンドを抽象化し、 Trident がボリュームの配置を決定できるようにします。管理者は仮想プールを `backend.json`ファイル。ストレージ クラスはセレクターを使用して、ラベルによって仮想プールを識別します。

* バックエンドで仮想プールが定義されている場合、 Trident はそれらの仮想プールが制限されている Google Cloud ストレージ プールにボリュームを作成しようとします。
* バックエンドで仮想プールが定義されていない場合、 Trident はリージョン内の利用可能なストレージ プールから Google Cloud ストレージ プールを選択します。


TridentでGoogle Cloudバックエンドを構成するには、以下を指定する必要があります。 `projectNumber` 、 `apiRegion` 、 そして `apiKey`バックエンドファイル内。プロジェクト番号は Google Cloud コンソールで確認できます。  API キーは、Google Cloud でCloud Volumes Serviceの API アクセスを設定するときに作成したサービス アカウントの秘密キー ファイルから取得されます。

Google CloudのCloud Volumes Serviceのサービスタイプとサービスレベルの詳細については、以下を参照してください。link:../trident-use/gcp.html["GCP 向け CVS のTridentサポートについて学ぶ"] 。

[cols="20,10,10,10,10,10,10"]
|===
| Google Cloud ドライバー用のCloud Volumes Service | Snapshot 数 | クローン | マルチアタッチ | QoS | 拡張 | レプリケーション 


| `gcp-cvs` | はい | はい | はい | はい | はい | CVS-Performance サービス タイプでのみ利用可能です。 
|===
[NOTE]
====
.レプリケーションノート
* レプリケーションはTridentによって管理されません。
* クローン は、ソース ボリュームと同じストレージ プールに作成されます。


====


== ストレージクラスの設計

Kubernetes ストレージ クラス オブジェクトを作成するには、個々のストレージ クラスを構成して適用する必要があります。このセクションでは、アプリケーションのストレージ クラスを設計する方法について説明します。



=== 特定のバックエンドの利用

特定のストレージ クラス オブジェクト内でフィルタリングを使用すると、その特定のストレージ クラスで使用されるストレージ プールまたはプール セットを決定できます。ストレージ クラスでは、次の 3 セットのフィルターを設定できます。 `storagePools` 、 `additionalStoragePools` 、および/または `excludeStoragePools`。

その `storagePools`パラメーターは、指定された属性に一致するプールのセットにストレージを制限するのに役立ちます。その `additionalStoragePools`パラメータは、属性によって選択されたプールのセットとともに、 Tridentがプロビジョニングに使用するプールのセットを拡張するために使用されます。 `storagePools`パラメータ。いずれかのパラメータを単独で、または両方を一緒に使用して、適切なストレージ プールのセットが選択されていることを確認できます。

その `excludeStoragePools`パラメータは、属性に一致するリストされたプールのセットを具体的に除外するために使用されます。



=== QoSポリシーをエミュレートする

ストレージクラスを設計してサービス品質ポリシーをエミュレートしたい場合は、 `media`属性として `hdd`または `ssd`。に基づいて `media`ストレージクラスで指定された属性に基づいて、 Tridentは適切なバックエンドを選択します。 `hdd`または `ssd`アグリゲートをメディア属性と一致させてから、特定のアグリゲートにボリュームのプロビジョニングを指示します。したがって、PREMIUMというストレージクラスを作成すると、 `media`属性設定 `ssd`これは PREMIUM QoS ポリシーとして分類できます。メディア属性を「hdd」に設定し、STANDARD QoS ポリシーとして分類できる別のストレージ クラス STANDARD を作成できます。また、ストレージ クラスの「IOPS」属性を使用して、QoS ポリシーとして定義できる Element アプライアンスにプロビジョニングをリダイレクトすることもできます。



=== 特定の機能に基づいてバックエンドを活用する

ストレージ クラスは、シン プロビジョニング、シック プロビジョニング、スナップショット、クローン、暗号化などの機能が有効になっている特定のバックエンドでボリュームのプロビジョニングを直接行うように設計できます。使用するストレージを指定するには、必要な機能が有効になっている適切なバックエンドを指定するストレージ クラスを作成します。



=== 仮想プール

仮想プールはすべてのTridentバックエンドで利用できます。  Trident が提供する任意のドライバーを使用して、任意のバックエンドの仮想プールを定義できます。

仮想プールを使用すると、管理者はストレージ クラスを通じて参照できるバックエンドの抽象化レベルを作成できるため、バックエンドでのボリュームの配置の柔軟性と効率性が向上します。同じサービス クラスで異なるバックエンドを定義できます。さらに、同じバックエンド上に、異なる特性を持つ複数のストレージ プールを作成することもできます。ストレージ クラスが特定のラベルを持つセレクタで構成されている場合、 Trident はすべてのセレクタ ラベルに一致するバックエンドを選択してボリュームを配置します。ストレージ クラス セレクターのラベルが複数のストレージ プールと一致する場合、 Trident はそのうちの 1 つを選択してボリュームをプロビジョニングします。



== 仮想プールの設計

バックエンドを作成する際には、一般的に一連のパラメータを指定できます。管理者が同じストレージ認証情報と異なるパラメータセットを持つ別のバックエンドを作成することは不可能でした。仮想プールの導入により、この問題は軽減されました。仮想プールは、バックエンドとKubernetesストレージクラスの間に導入されたレベル抽象化であり、管理者は、バックエンドに依存しない方法で、Kubernetesストレージクラスを介してセレクタとして参照できるラベルとともにパラメータを定義できます。仮想プールは、 Tridentを使用してサポートされているすべてのNetAppバックエンドに対して定義できます。そのリストには、 SolidFire/ NetApp HCI、 ONTAP、GCPのCloud Volumes Service 、 Azure NetApp Filesが含まれます。


NOTE: 仮想プールを定義するときは、バックエンド定義内の既存の仮想プールの順序を変更しないことをお勧めします。既存の仮想プールの属性を編集/変更せず、代わりに新しい仮想プールを定義することもお勧めします。



=== 異なるサービスレベル/QoSのエミュレーション

サービス クラスをエミュレートするための仮想プールを設計することが可能です。 Cloud Volume Service for Azure NetApp Filesの仮想プール実装を使用して、さまざまなサービス クラスを設定する方法を調べてみましょう。異なるパフォーマンス レベルを表す複数のラベルを使用して、 Azure NetApp Filesバックエンドを構成します。セット `servicelevel`側面を適切なパフォーマンス レベルに設定し、各ラベルの下にその他の必要な側面を追加します。次に、異なる仮想プールにマップする異なる Kubernetes ストレージ クラスを作成します。使用して `parameters.selector`フィールドでは、各 StorageClass はボリュームをホストするために使用できる仮想プールを呼び出します。



=== 特定の側面のセットを割り当てる

単一のストレージ バックエンドから、特定の側面を持つ複数の仮想プールを設計できます。そのためには、バックエンドを複数のラベルで構成し、各ラベルの下に必要な側面を設定します。次に、Kubernetesストレージクラスを作成します。 `parameters.selector`異なる仮想プールにマップされるフィールド。バックエンドでプロビジョニングされるボリュームには、選択した仮想プールで定義された側面が設定されます。



=== ストレージのプロビジョニングに影響するPVCの特性

要求されたストレージ クラスを超える一部のパラメーターは、PVC の作成時にTridentプロビジョニングの決定プロセスに影響を与える可能性があります。



=== アクセス モード

PVC 経由でストレージを要求する場合、必須フィールドの 1 つはアクセス モードです。希望するモードは、ストレージ要求をホストするために選択されたバックエンドに影響する可能性があります。

Trident は、次のマトリックスに従って、使用されるストレージ プロトコルと指定されたアクセス メソッドを一致させようとします。これは、基盤となるストレージ プラットフォームとは独立しています。

[cols="20,30,30,30"]
|===
|  | 一度だけ読み書き可能 | 読み取り専用 | 読み取り書き込み多数 


| iSCSI | はい | はい | はい（生のブロック） 


| NFS | はい | はい | はい 
|===
NFS バックエンドが構成されていないTridentデプロイメントに ReadWriteMany PVC の要求を送信すると、ボリュームはプロビジョニングされません。このため、リクエスト側はアプリケーションに適したアクセス モードを使用する必要があります。



== ボリューム操作



=== 永続ボリュームを変更する

永続ボリュームは、2 つの例外を除き、Kubernetes 内の不変オブジェクトです。作成したら、再利用ポリシーとサイズを変更できます。ただし、これによってボリュームの一部の側面が Kubernetes の外部で変更されるのを防ぐことはできません。これは、特定のアプリケーション用にボリュームをカスタマイズしたり、容量が誤って消費されないようにしたり、あるいは何らかの理由でボリュームを別のストレージ コントローラに移動したりする場合に望ましいことがあります。


NOTE: Kubernetes のツリー内プロビジョナーは、現時点では NFS、iSCSI、または FC PV のボリューム サイズ変更操作をサポートしていません。  Trident は、 NFS、iSCSI、FC ボリュームの拡張をサポートします。

PV の接続詳細は作成後に変更できません。



=== オンデマンドのボリュームスナップショットを作成する

Trident は、 CSI フレームワークを使用したオンデマンドのボリューム スナップショットの作成とスナップショットからの PVC の作成をサポートします。スナップショットは、データの特定時点のコピーを維持する便利な方法を提供し、Kubernetes のソース PV から独立したライフサイクルを持ちます。これらのスナップショットを使用して PVC を複製できます。



=== スナップショットからボリュームを作成する

Trident は、ボリューム スナップショットからの PersistentVolume の作成もサポートしています。これを実現するには、PersistentVolumeClaimを作成し、 `datasource`ボリュームを作成するために必要なスナップショットとして。 Trident は、スナップショットに存在するデータを含むボリュームを作成することで、この PVC を処理します。この機能を使用すると、リージョン間でデータを複製したり、テスト環境を作成したり、破損または壊れた本番ボリューム全体を交換したり、特定のファイルやディレクトリを取得して別の接続されたボリュームに転送したりすることが可能になります。



=== クラスター内のボリュームを移動する

ストレージ管理者は、ストレージ コンシューマーに支障をきたすことなく、 ONTAPクラスタ内のアグリゲートとコントローラ間でボリュームを移動できます。宛先アグリゲートがTridentが使用している SVM がアクセスできるものである限り、この操作はTridentまたは Kubernetes クラスターに影響を与えません。重要なのは、集計が SVM に新しく追加された場合、それをTridentに再度追加してバックエンドを更新する必要があることです。これにより、 Trident はSVM の再インベントリを実行し、新しいアグリゲートが認識されるようになります。

ただし、バックエンド間でのボリュームの移動は、 Tridentでは自動的にはサポートされません。これには、同じクラスター内の SVM 間、クラスター間、または異なるストレージ プラットフォーム (そのストレージ システムがTridentに接続されている場合も含む) が含まれます。

ボリュームを別の場所にコピーする場合は、ボリューム インポート機能を使用して現在のボリュームをTridentにインポートできます。



=== ボリュームを拡張する

Trident は、 NFS、iSCSI、および FC PV のサイズ変更をサポートしています。これにより、ユーザーは Kubernetes レイヤーを通じてボリュームのサイズを直接変更できるようになります。ボリューム拡張は、 ONTAP、 SolidFire/ NetApp HCI 、 Cloud Volumes Serviceバックエンドを含むすべての主要なNetAppストレージ プラットフォームで可能です。後で拡張できるように設定するには `allowVolumeExpansion`に `true`ボリュームに関連付けられた StorageClass 内。永続ボリュームのサイズを変更する必要がある場合は、 `spec.resources.requests.storage`永続ボリューム要求の注釈を必要なボリューム サイズに設定します。  Trident は、ストレージ クラスター上のボリュームのサイズ変更を自動的に処理します。



=== 既存のボリュームをKubernetesにインポートする

ボリューム インポートでは、既存のストレージ ボリュームを Kubernetes 環境にインポートできます。これは現在、 `ontap-nas` 、 `ontap-nas-flexgroup` 、 `solidfire-san` 、 `azure-netapp-files` 、 そして `gcp-cvs`ドライバー。この機能は、既存のアプリケーションを Kubernetes に移植する場合や、災害復旧シナリオ時に役立ちます。

ONTAPを使用する場合 `solidfire-san`ドライバーの場合は、コマンド `tridentctl import volume <backend-name> <volume-name> -f /path/pvc.yaml`既存のボリュームを Kubernetes にインポートして、 Tridentで管理できるようにします。インポート ボリューム コマンドで使用される PVC YAML または JSON ファイルは、 Trident をプロビジョナーとして識別するストレージ クラスを指します。 NetApp HCI/ SolidFireバックエンドを使用する場合は、ボリューム名が一意であることを確認してください。ボリューム名が重複している場合は、ボリュームのインポート機能で区別できるように、ボリュームを一意の名前で複製します。

もし `azure-netapp-files`または `gcp-cvs`ドライバーを使用する場合は、コマンド `tridentctl import volume <backend-name> <volume path> -f /path/pvc.yaml`Tridentで管理できるようにボリュームを Kubernetes にインポートします。これにより、一意のボリューム参照が保証されます。

上記のコマンドを実行すると、 Trident はバックエンド上のボリュームを見つけてそのサイズを読み取ります。設定された PVC のボリューム サイズが自動的に追加され (必要に応じて上書きされます)。次に、 Trident は新しい PV を作成し、Kubernetes は PVC を PV にバインドします。

特定のインポートされた PVC を必要とするコンテナーがデプロイされた場合、PVC/PV ペアがボリューム インポート プロセスによってバインドされるまで、コンテナーは保留状態のままになります。  PVC/PV ペアがバインドされた後、他の問題がなければコンテナーが起動するはずです。



=== レジストリサービス

レジストリのストレージの展開と管理については、link:https://netapp.io/["ネットアップ"^]の中でlink:https://netapp.io/2017/08/24/deploying-the-openshift-registry-using-netapp-storage/["ブログ"^]。



=== ログサービス

他の OpenShift サービスと同様に、ログ サービスは、プレイブックに提供されるインベントリ ファイル (ホスト) によって提供される構成パラメーターを使用して Ansible を使用してデプロイされます。説明するインストール方法は 2 つあります。OpenShift の初期インストール時にログをデプロイする方法と、OpenShift のインストール後にログをデプロイする方法です。


CAUTION: Red Hat OpenShift バージョン 3.9 の時点では、データ破損の懸念があるため、公式ドキュメントではログ サービスに NFS を使用しないことを推奨しています。これは Red Hat による自社製品のテストに基づいています。 ONTAP NFS サーバーにはこれらの問題はなく、ログの展開を簡単にバックアップできます。最終的に、ログ サービスのプロトコルの選択はユーザー次第ですが、 NetAppプラットフォームを使用する場合はどちらも問題なく機能し、NFS が好みであれば NFS を避ける理由はありません。

ログサービスでNFSを使用する場合は、Ansible変数を設定する必要があります。 `openshift_enable_unsupported_configurations`に `true`インストーラーが失敗するのを防ぐためです。



==== 始めましょう

オプションで、ログ サービスは、アプリケーションだけでなく、OpenShift クラスター自体のコア操作にもデプロイできます。操作ログを展開することを選択した場合は、変数を指定して `openshift_logging_use_ops`として `true`、サービスのインスタンスが 2 つ作成されます。操作のログインスタンスを制御する変数には「ops」が含まれますが、アプリケーションのインスタンスには含まれません。

基盤となるサービスによって正しいストレージが確実に利用されるようにするには、デプロイメント方法に応じて Ansible 変数を構成することが重要です。それぞれの展開方法のオプションを見てみましょう。


NOTE: 以下の表には、ログ サービスに関連するストレージ構成に関係する変数のみが含まれています。その他のオプションについては、link:https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html["Red Hat OpenShift のログ記録ドキュメント"^]これらは、展開に応じて確認、構成、および使用する必要があります。

以下の表の変数により、Ansible プレイブックは提供された詳細を使用して、ログ サービス用の PV と PVC を作成します。この方法は、OpenShift のインストール後にコンポーネント インストール プレイブックを使用するよりも柔軟性が大幅に低くなりますが、既存のボリュームが利用できる場合はオプションとして使用できます。

[cols="40,40"]
|===
| 変数 | 詳細 


| `openshift_logging_storage_kind` | 設定 `nfs`インストーラーでログ サービス用の NFS PV を作成します。 


| `openshift_logging_storage_host` | NFS ホストのホスト名または IP アドレス。これは仮想マシンの dataLIF に設定する必要があります。 


| `openshift_logging_storage_nfs_directory` | NFS エクスポートのマウント パス。たとえば、ボリュームが次のようにジャンクションされている場合 `/openshift_logging`、この変数にはそのパスを使用します。 


| `openshift_logging_storage_volume_name` | 名前、例 `pv_ose_logs`、作成するPVの。 


| `openshift_logging_storage_volume_size` | NFSエクスポートのサイズ、例 `100Gi`。 
|===
OpenShift クラスターがすでに実行されており、 Trident がデプロイおよび構成されている場合は、インストーラーは動的プロビジョニングを使用してボリュームを作成できます。次の変数を設定する必要があります。

[cols="40,40"]
|===
| 変数 | 詳細 


| `openshift_logging_es_pvc_dynamic` | 動的にプロビジョニングされたボリュームを使用するには、true に設定します。 


| `openshift_logging_es_pvc_storage_class_name` | PVC で使用されるストレージ クラスの名前。 


| `openshift_logging_es_pvc_size` | PVC で要求されたボリュームのサイズ。 


| `openshift_logging_es_pvc_prefix` | ログ サービスによって使用される PVC のプレフィックス。 


| `openshift_logging_es_ops_pvc_dynamic` | 設定 `true`オペレーションログインスタンスに動的にプロビジョニングされたボリュームを使用します。 


| `openshift_logging_es_ops_pvc_storage_class_name` | オペレーションログインスタンスのストレージクラスの名前。 


| `openshift_logging_es_ops_pvc_size` | オペレーションインスタンスのボリューム要求のサイズ。 


| `openshift_logging_es_ops_pvc_prefix` | ops インスタンス PVC のプレフィックス。 
|===


==== ログスタックをデプロイする

ログ記録を OpenShift の初期インストール プロセスの一部としてデプロイする場合は、標準のデプロイ プロセスに従うだけで済みます。  Ansible は必要なサービスと OpenShift オブジェクトを構成およびデプロイし、Ansible が完了するとすぐにサービスが利用できるようになります。

ただし、初期インストール後にデプロイする場合は、Ansible でコンポーネント プレイブックを使用する必要があります。このプロセスはOpenShiftのバージョンによって多少異なる可能性がありますので、必ず読んで従ってください。link:https://docs.openshift.com/container-platform/3.11/welcome/index.html["Red Hat OpenShift Container Platform 3.11 ドキュメント"^]あなたのバージョン用。



== メトリクスサービス

メトリクス サービスは、OpenShift クラスターのステータス、リソース使用率、可用性に関する貴重な情報を管理者に提供します。これはポッドの自動スケール機能にも必要であり、多くの組織はチャージバックやショーバック アプリケーションにメトリック サービスのデータを使用しています。

ログ サービスや OpenShift 全体と同様に、メトリック サービスのデプロイには Ansible が使用されます。また、ログ サービスと同様に、メトリック サービスは、クラスターの初期セットアップ時、またはコンポーネント インストール方法を使用して運用開始後にデプロイできます。次の表には、メトリック サービスの永続ストレージを構成するときに重要な変数が含まれています。


NOTE: 以下の表には、メトリック サービスに関連するストレージ構成に関係する変数のみが含まれています。ドキュメントには他にも多くのオプションが記載されており、展開に応じて確認、構成、使用する必要があります。

[cols="40,40"]
|===
| 変数 | 詳細 


| `openshift_metrics_storage_kind` | 設定 `nfs`インストーラーでログ サービス用の NFS PV を作成します。 


| `openshift_metrics_storage_host` | NFS ホストのホスト名または IP アドレス。これは、SVM の dataLIF に設定する必要があります。 


| `openshift_metrics_storage_nfs_directory` | NFS エクスポートのマウント パス。たとえば、ボリュームが次のようにジャンクションされている場合 `/openshift_metrics`、この変数にはそのパスを使用します。 


| `openshift_metrics_storage_volume_name` | 名前、例 `pv_ose_metrics`、作成するPVの。 


| `openshift_metrics_storage_volume_size` | NFSエクスポートのサイズ、例 `100Gi`。 
|===
OpenShift クラスターがすでに実行されており、 Trident がデプロイおよび構成されている場合は、インストーラーは動的プロビジョニングを使用してボリュームを作成できます。次の変数を設定する必要があります。

[cols="40,40"]
|===
| 変数 | 詳細 


| `openshift_metrics_cassandra_pvc_prefix` | メトリック PVC に使用するプレフィックス。 


| `openshift_metrics_cassandra_pvc_size` | 要求するボリュームのサイズ。 


| `openshift_metrics_cassandra_storage_type` | メトリックに使用するストレージのタイプ。Ansible が適切なストレージ クラスを持つ PVC を作成するには、これを dynamic に設定する必要があります。 


| `openshift_metrics_cassanda_pvc_storage_class_name` | 使用するストレージ クラスの名前。 
|===


=== メトリクスサービスをデプロイする

hosts/inventory ファイルに適切な Ansible 変数を定義して、Ansible を使用してサービスをデプロイします。 OpenShift のインストール時にデプロイする場合は、PV が自動的に作成され、使用されます。コンポーネント プレイブックを使用してデプロイする場合は、OpenShift のインストール後に Ansible が必要な PVC を作成し、 Trident がそれらのストレージをプロビジョニングした後、サービスをデプロイします。

上記の変数とデプロイのプロセスは、OpenShift のバージョンごとに変更される可能性があります。必ず確認して従ってくださいlink:https://docs.openshift.com/container-platform/3.11/install_config/cluster_metrics.html["Red HatのOpenShiftデプロイメントガイド"^]お使いの環境に合わせて構成されるように、バージョンに応じて変更してください。
