---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: 新しい機能やバグ修正を利用するには、 Trident Protect を最新バージョンにアップグレードできます。 
---
= Tridentプロテクトのアップグレード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
新しい機能やバグ修正を利用するには、 Trident Protect を最新バージョンにアップグレードできます。

[NOTE]
====
バージョン 24.10 からアップグレードすると、アップグレード中に実行されるスナップショットが失敗する可能性があります。この障害により、手動またはスケジュールされた将来のスナップショットの作成が妨げられることはありません。アップグレード中にスナップショットが失敗した場合は、アプリケーションが保護されるように手動で新しいスナップショットを作成できます。

潜在的な障害を回避するために、アップグレード前にすべてのスナップショット スケジュールを無効にして、アップグレード後に再度有効にすることができます。ただし、これにより、アップグレード期間中にスケジュールされたスナップショットが失われることになります。

====
Trident Protect をアップグレードするには、次の手順を実行します。

.手順
. Trident Helm リポジトリを更新します。
+
[source, console]
----
helm repo update
----
. Trident Protect CRD をアップグレードします。
+

NOTE: 25.06 より前のバージョンからアップグレードする場合は、CRD がTrident Protect Helm チャートに含まれるようになったため、この手順は必須です。

+
.. このコマンドを実行すると、CRDの管理を `trident-protect-crds`に `trident-protect`:
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. このコマンドを実行してHelmシークレットを削除します `trident-protect-crds`チャート：
+

NOTE: アンインストールしないでください `trident-protect-crds`Helm を使用してチャートを作成しないでください。CRD と関連データが削除される可能性があります。

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Tridentプロテクトのアップグレード:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2506.0 --namespace trident-protect
----

