---
sidebar: sidebar 
permalink: trident-protect/trident-protect-restore-settings.html 
keywords: trident, protect, restore, data, backup 
summary: 注釈、名前空間設定、およびストレージ オプションを使用して、 Trident Protect の復元操作をカスタマイズできます。 
---
= 高度なTrident Protect復元設定を使用する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
注釈、名前空間設定、ストレージ オプションなどの詳細設定を使用して、特定の要件を満たすように復元操作をカスタマイズできます。



[[namespace-annotations-and-labels-during-restore-and-failover-operations]]
== 復元およびフェイルオーバー操作中の名前空間の注釈とラベル

復元およびフェイルオーバー操作中に、宛先名前空間のラベルと注釈は、ソース名前空間のラベルと注釈と一致するように作成されます。宛先名前空間に存在しないソース名前空間のラベルまたは注釈が追加され、既存のラベルまたは注釈はソース名前空間の値と一致するように上書きされます。宛先名前空間にのみ存在するラベルまたは注釈は変更されません。


NOTE: Red Hat OpenShift を使用する場合は、OpenShift 環境における名前空間アノテーションの重要な役割に注意することが重要です。名前空間アノテーションにより、復元されたポッドが OpenShift のセキュリティ コンテキスト制約 (SCC) によって定義された適切な権限とセキュリティ構成に準拠し、権限の問題なくボリュームにアクセスできるようになります。詳細については、 https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/authentication_and_authorization/managing-pod-security-policies["OpenShift セキュリティ コンテキスト制約のドキュメント"^] 。

Kubernetes環境変数を設定することで、宛先名前空間内の特定のアノテーションが上書きされるのを防ぐことができます。 `RESTORE_SKIP_NAMESPACE_ANNOTATIONS`復元またはフェイルオーバー操作を実行する前に。例えば：

[source, console]
----
helm upgrade trident-protect --set restoreSkipNamespaceAnnotations=<annotation_key_to_skip_1>,<annotation_key_to_skip_2> --reuse-values
----

NOTE: リストアまたはフェイルオーバー操作を実行すると、 `restoreSkipNamespaceAnnotations`および `restoreSkipNamespaceLabels`で指定された名前空間アノテーションとラベルは、リストアまたはフェイルオーバー操作から除外されます。これらの設定は、Helmの初回インストール時に必ず構成してください。詳細については、link:../trident-protect/trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["追加のTrident Protectヘルムチャート設定を構成する"] を参照してください。

ソースアプリケーションをHelmを使用してインストールした場合、 `--create-namespace`旗には特別な扱いが与えられます `name`ラベルキー。復元またはフェイルオーバー プロセス中に、 Trident Protect はこのラベルを宛先名前空間にコピーしますが、ソースからの値がソース名前空間と一致する場合は、値を宛先名前空間の値に更新します。この値がソース名前空間と一致しない場合は、変更されずに宛先名前空間にコピーされます。



[[example]]
=== 例

次の例は、それぞれ異なる注釈とラベルを持つソース名前空間と宛先名前空間を示しています。操作の前後の宛先名前空間の状態や、宛先名前空間で注釈とラベルがどのように結合または上書きされるかを確認できます。



==== 復元またはフェイルオーバー操作の前に

次の表は、復元またはフェイルオーバー操作前のサンプルのソース名前空間と宛先名前空間の状態を示しています。

[cols="1,2a,2a"]
|===
| ネームスペース | アノテーション | ラベル 


| 名前空間 ns-1 (ソース)  a| 
* アノテーション.one/キー: "更新された値"
* アノテーション.2/キー: "true"

 a| 
* 環境=本番環境
* コンプライアンス=HIPAA
* 名前=ns-1




| 名前空間 ns-2 (宛先)  a| 
* アノテーション.one/キー: "true"
* 注釈.three/キー: "false"

 a| 
* 役割=データベース


|===


==== 復元操作後

次の表は、復元またはフェイルオーバー操作後の宛先名前空間の例の状態を示しています。いくつかのキーが追加され、いくつかは上書きされ、 `name`ラベルは宛先名前空間と一致するように更新されました:

[cols="1,2a,2a"]
|===
| ネームスペース | アノテーション | ラベル 


| 名前空間 ns-2 (宛先)  a| 
* アノテーション.one/キー: "更新された値"
* アノテーション.2/キー: "true"
* 注釈.three/キー: "false"

 a| 
* 名前=ns-2
* コンプライアンス=HIPAA
* 環境=本番環境
* 役割=データベース


|===


[[supported-fields]]
== サポートされているフィールド

このセクションでは、復元操作に使用できる追加のフィールドについて説明します。



[[storage-class-mapping]]
=== ストレージクラスのマッピング

その `spec.storageClassMapping`属性は、ソース アプリケーションに存在するストレージ クラスからターゲット クラスター上の新しいストレージ クラスへのマッピングを定義します。これは、異なるストレージ クラスを持つクラスター間でアプリケーションを移行する場合や、BackupRestore 操作のストレージ バックエンドを変更する場合に使用できます。

*例：*

[source, yaml]
----
storageClassMapping:
  - destination: "destinationStorageClass1"
    source: "sourceStorageClass1"
  - destination: "destinationStorageClass2"
    source: "sourceStorageClass2"
----


[[supported-annotations]]
== サポートされている注釈

このセクションでは、システム内のさまざまな動作を構成するためにサポートされているアノテーションを一覧表示します。ユーザーが注釈を明示的に設定しない場合、システムはデフォルト値を使用します。

[cols="1,1,3,1"]
|===
| 注釈 | タイプ | 説明 | デフォルト値 


| protect.trident.netapp.io/データムーバータイムアウト秒 | string | データ ムーバー操作を停止できる最大時間 (秒単位)。 | 「300」 


| protect.trident.netapp.io/kopia-content-cache-size-limit-mb | string | Kopia コンテンツ キャッシュの最大サイズ制限 (メガバイト単位)。 | 「1000」 
|===