---
sidebar: sidebar 
permalink: trident-protect/trident-protect-requirements.html 
keywords: trident protect, application, cluster, snapmirror replication, ontap, configuration 
summary: まず、運用環境、アプリケーション クラスター、アプリケーション、ライセンスの準備状況を確認します。  Trident Protect を展開および運用するには、環境がこれらの要件を満たしていることを確認してください。 
---
= Trident保護要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
まず、運用環境、アプリケーション クラスター、アプリケーション、ライセンスの準備状況を確認します。  Trident Protect を展開および運用するには、環境がこれらの要件を満たしていることを確認してください。



== Trident はKubernetes クラスターの互換性を保護します

Trident Protect は、以下を含む幅広いフルマネージドおよびセルフマネージド Kubernetes 製品と互換性があります。

* Amazon Elastic Kubernetes サービス (EKS)
* Google Kubernetes Engine (GKE)
* Microsoft Azure Kubernetes サービス (AKS)
* レッドハット オープンシフト
* SUSE ランチャー
* VMware Tanzu ポートフォリオ
* アップストリームKubernetes


[NOTE]
====
* Trident Protect バックアップは、Linux コンピューティング ノードでのみサポートされます。Windows コンピューティング ノードはバックアップ操作ではサポートされていません。
* Trident Protect をインストールするクラスターに、実行中のスナップショット コントローラーと関連する CRD が設定されていることを確認します。スナップショットコントローラをインストールするには、 https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploy-a-volume-snapshot-controller["これらの指示"] 。


====


== Trident はストレージバックエンドの互換性を保護します

Trident Protect は次のストレージ バックエンドをサポートしています。

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP
* ONTAPストレージアレイ
* Google Cloud NetApp Volumes
* Azure NetApp Files


ストレージ バックエンドが次の要件を満たしていることを確認します。

* クラスターに接続されているNetAppストレージがTrident 24.02 以降を使用していることを確認します (Trident 24.10 を推奨)。


* NetApp ONTAPストレージ バックエンドがあることを確認します。
* バックアップを保存するためのオブジェクト ストレージ バケットが設定されていることを確認します。
* アプリケーションまたはアプリケーション データ管理操作に使用する予定のアプリケーション名前空間を作成します。  Trident protect はこれらの名前空間を作成しません。カスタム リソースに存在しない名前空間を指定すると、操作は失敗します。




== NASエコノミーボリュームの要件

Trident Protect は、NAS エコノミー ボリュームへのバックアップおよび復元操作をサポートします。スナップショット、クローン、および NAS エコノミー ボリュームへのSnapMirrorレプリケーションは現在サポートされていません。  Trident Protect で使用する予定の各 nas-economy ボリュームに対してスナップショット ディレクトリを有効にする必要があります。

[NOTE]
====
一部のアプリケーションは、スナップショット ディレクトリを使用するボリュームと互換性がありません。これらのアプリケーションでは、 ONTAPストレージ システムで次のコマンドを実行して、スナップショット ディレクトリを非表示にする必要があります。

[source, console]
----
nfs modify -vserver <svm> -v3-hide-snapshot enabled
----
====
スナップショットディレクトリを有効にするには、各nas-economyボリュームに対して次のコマンドを実行し、 `<volume-UUID>`変更したいボリュームのUUIDに置き換えます。

[source, console]
----
tridentctl update volume <volume-UUID> --snapshot-dir=true --pool-level=true -n trident
----

NOTE: Tridentバックエンド設定オプションを設定することで、新しいボリュームのスナップショットディレクトリをデフォルトで有効にすることができます。 `snapshotDir`に `true`。既存のボリュームは影響を受けません。



== KubeVirt VM によるデータ保護

Trident protect 24.10 と 24.10.1 以降では、KubeVirt VM 上で実行されているアプリケーションを保護する場合の動作が異なります。どちらのバージョンでも、データ保護操作中にファイルシステムのフリーズとフリーズ解除を有効または無効にすることができます。


NOTE: 復元操作中は、 `VirtualMachineSnapshots`仮想マシン (VM) 用に作成されたファイルは復元されません。

.Tridentプロテクト 24.10
Trident protect 24.10 は、データ保護操作中に KubeVirt VM ファイルシステムの一貫した状態を自動的に保証しません。 Trident protect 24.10 を使用して KubeVirt VM データを保護する場合は、データ保護操作の前に、ファイルシステムのフリーズ/アンフリーズ機能を手動で有効にする必要があります。これにより、ファイルシステムが一貫した状態になることが保証されます。

Trident protect 24.10を設定して、データ保護操作中にVMファイルシステムの凍結と解凍を管理することができます。link:https://docs.openshift.com/container-platform/4.16/virt/install/installing-virt.html["仮想化の構成"^]そして次のコマンドを使用します。

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=true -n trident-protect
----
.Trident Protect 24.10.1以降
Trident protect 24.10.1 以降、 Trident protect はデータ保護操作中に KubeVirt ファイルシステムを自動的にフリーズおよびアンフリーズします。オプションで、次のコマンドを使用してこの自動動作を無効にすることができます。

[source, console]
----
kubectl set env deployment/trident-protect-controller-manager NEPTUNE_VM_FREEZE=false -n trident-protect
----


== SnapMirrorレプリケーションの要件

NetApp SnapMirrorレプリケーションは、次のONTAPソリューションのTrident Protect で使用できます。

* オンプレミスのNetApp FAS、 AFF、 ASAクラスター
* NetApp ONTAP Select
* NetAppCloud Volumes ONTAP
* Amazon FSx for NetApp ONTAP




=== SnapMirrorレプリケーションのONTAPクラスタ要件

SnapMirrorレプリケーションを使用する予定の場合は、 ONTAPクラスタが次の要件を満たしていることを確認してください。

* * NetApp Trident*: NetApp Trident は、 ONTAP をバックエンドとして使用するソース Kubernetes クラスターと宛先 Kubernetes クラスターの両方に存在する必要があります。  Trident Protect は、次のドライバーによってサポートされるストレージ クラスを使用して、 NetApp SnapMirrorテクノロジによるレプリケーションをサポートします。
+
** `ontap-nas`: NFS
** `ontap-san`: iSCSI
** `ontap-san`: FC
** `ontap-san`: NVMe/TCP (最低でもONTAPバージョン 9.15.1 が必要)


* *ライセンス*: データ保護バンドルを使用するONTAP SnapMirror非同期ライセンスは、ソースと宛先の両方のONTAPクラスタで有効にする必要があります。参照 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["ONTAPにおけるSnapMirrorライセンスの概要"^]詳細についてはこちらをご覧ください。
+
ONTAP 9.10.1以降では、すべてのライセンスがNetAppライセンス ファイル（NLF）として提供されます。これは、複数の機能を有効にする単一のファイルです。参照link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP Oneに含まれるライセンス"^]詳細についてはこちらをご覧ください。

+

NOTE: SnapMirror非同期保護のみがサポートされます。





=== SnapMirrorレプリケーションのピアリングに関する考慮事項

ストレージ バックエンド ピアリングを使用する予定の場合は、環境が次の要件を満たしていることを確認してください。

* *クラスタと SVM*: ONTAPストレージ バックエンドをピアリングする必要があります。参照 https://docs.netapp.com/us-en/ontap/peering/index.html["クラスタとSVMのピアリングの概要"^]詳細についてはこちらをご覧ください。
+

NOTE: 2 つのONTAPクラスタ間のレプリケーション関係で使用される SVM 名が一意であることを確認します。

* * NetApp Tridentと SVM*: ピアリングされたリモート SVM は、宛先クラスタ上のNetApp Tridentで使用できる必要があります。
* *管理対象バックエンド*: レプリケーション関係を作成するには、 Trident Protect でONTAPストレージ バックエンドを追加および管理する必要があります。




=== SnapMirrorレプリケーションのためのTrident / ONTAP構成

Trident Protect では、ソース クラスターと宛先クラスターの両方のレプリケーションをサポートするストレージ バックエンドを少なくとも 1 つ構成する必要があります。ソース クラスターと宛先クラスターが同じ場合、復元力を最大限に高めるには、宛先アプリケーションでソース アプリケーションとは異なるストレージ バックエンドを使用する必要があります。



=== SnapMirrorレプリケーションのKubernetesクラスタ要件

Kubernetes クラスターが次の要件を満たしていることを確認します。

* *AppVault のアクセシビリティ*: アプリケーション オブジェクトのレプリケーションでは、ソース クラスターと宛先クラスターの両方に、AppVault の読み取りと書き込みを行うためのネットワーク アクセスが必要です。
* *ネットワーク接続*: ファイアウォール ルール、バケット権限、IP 許可リストを構成して、WAN を介した両方のクラスターと AppVault 間の通信を有効にします。



NOTE: 多くの企業環境では、WAN 接続全体に厳格なファイアウォール ポリシーが実装されています。レプリケーションを構成する前に、インフラストラクチャ チームとこれらのネットワーク要件を確認してください。
